-- nios_system.vhd

-- Generated using ACDS version 13.1 162 at 2026.05.20.14:26:06

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity nios_system is
	port (
		clk_clk                     : in    std_logic                     := '0';             --                  clk.clk
		reset_reset_n               : in    std_logic                     := '0';             --                reset.reset_n
		switches_export             : in    std_logic_vector(7 downto 0)  := (others => '0'); --             switches.export
		leds_export                 : out   std_logic_vector(7 downto 0);                     --                 leds.export
		sdram_wire_addr             : out   std_logic_vector(12 downto 0);                    --           sdram_wire.addr
		sdram_wire_ba               : out   std_logic_vector(1 downto 0);                     --                     .ba
		sdram_wire_cas_n            : out   std_logic;                                        --                     .cas_n
		sdram_wire_cke              : out   std_logic;                                        --                     .cke
		sdram_wire_cs_n             : out   std_logic;                                        --                     .cs_n
		sdram_wire_dq               : inout std_logic_vector(15 downto 0) := (others => '0'); --                     .dq
		sdram_wire_dqm              : out   std_logic_vector(1 downto 0);                     --                     .dqm
		sdram_wire_ras_n            : out   std_logic;                                        --                     .ras_n
		sdram_wire_we_n             : out   std_logic;                                        --                     .we_n
		pwm_avalon_interface_export : out   std_logic_vector(3 downto 0)                      -- pwm_avalon_interface.export
	);
end entity nios_system;

architecture rtl of nios_system is
	component nios_system_CPU is
		port (
			clk                                   : in  std_logic                     := 'X';             -- clk
			reset_n                               : in  std_logic                     := 'X';             -- reset_n
			reset_req                             : in  std_logic                     := 'X';             -- reset_req
			d_address                             : out std_logic_vector(26 downto 0);                    -- address
			d_byteenable                          : out std_logic_vector(3 downto 0);                     -- byteenable
			d_read                                : out std_logic;                                        -- read
			d_readdata                            : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			d_waitrequest                         : in  std_logic                     := 'X';             -- waitrequest
			d_write                               : out std_logic;                                        -- write
			d_writedata                           : out std_logic_vector(31 downto 0);                    -- writedata
			jtag_debug_module_debugaccess_to_roms : out std_logic;                                        -- debugaccess
			i_address                             : out std_logic_vector(26 downto 0);                    -- address
			i_read                                : out std_logic;                                        -- read
			i_readdata                            : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			i_waitrequest                         : in  std_logic                     := 'X';             -- waitrequest
			d_irq                                 : in  std_logic_vector(31 downto 0) := (others => 'X'); -- irq
			jtag_debug_module_resetrequest        : out std_logic;                                        -- reset
			jtag_debug_module_address             : in  std_logic_vector(8 downto 0)  := (others => 'X'); -- address
			jtag_debug_module_byteenable          : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- byteenable
			jtag_debug_module_debugaccess         : in  std_logic                     := 'X';             -- debugaccess
			jtag_debug_module_read                : in  std_logic                     := 'X';             -- read
			jtag_debug_module_readdata            : out std_logic_vector(31 downto 0);                    -- readdata
			jtag_debug_module_waitrequest         : out std_logic;                                        -- waitrequest
			jtag_debug_module_write               : in  std_logic                     := 'X';             -- write
			jtag_debug_module_writedata           : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			no_ci_readra                          : out std_logic                                         -- readra
		);
	end component nios_system_CPU;

	component nios_system_MEMOIRE_INTERNE is
		port (
			clk        : in  std_logic                     := 'X';             -- clk
			address    : in  std_logic_vector(9 downto 0)  := (others => 'X'); -- address
			clken      : in  std_logic                     := 'X';             -- clken
			chipselect : in  std_logic                     := 'X';             -- chipselect
			write      : in  std_logic                     := 'X';             -- write
			readdata   : out std_logic_vector(31 downto 0);                    -- readdata
			writedata  : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			byteenable : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- byteenable
			reset      : in  std_logic                     := 'X';             -- reset
			reset_req  : in  std_logic                     := 'X'              -- reset_req
		);
	end component nios_system_MEMOIRE_INTERNE;

	component nios_system_INPUT is
		port (
			clk      : in  std_logic                     := 'X';             -- clk
			reset_n  : in  std_logic                     := 'X';             -- reset_n
			address  : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- address
			readdata : out std_logic_vector(31 downto 0);                    -- readdata
			in_port  : in  std_logic_vector(7 downto 0)  := (others => 'X')  -- export
		);
	end component nios_system_INPUT;

	component nios_system_OUTPUT is
		port (
			clk        : in  std_logic                     := 'X';             -- clk
			reset_n    : in  std_logic                     := 'X';             -- reset_n
			address    : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- address
			write_n    : in  std_logic                     := 'X';             -- write_n
			writedata  : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			chipselect : in  std_logic                     := 'X';             -- chipselect
			readdata   : out std_logic_vector(31 downto 0);                    -- readdata
			out_port   : out std_logic_vector(7 downto 0)                      -- export
		);
	end component nios_system_OUTPUT;

	component nios_system_JTAG_UART is
		port (
			clk            : in  std_logic                     := 'X';             -- clk
			rst_n          : in  std_logic                     := 'X';             -- reset_n
			av_chipselect  : in  std_logic                     := 'X';             -- chipselect
			av_address     : in  std_logic                     := 'X';             -- address
			av_read_n      : in  std_logic                     := 'X';             -- read_n
			av_readdata    : out std_logic_vector(31 downto 0);                    -- readdata
			av_write_n     : in  std_logic                     := 'X';             -- write_n
			av_writedata   : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			av_waitrequest : out std_logic;                                        -- waitrequest
			av_irq         : out std_logic                                         -- irq
		);
	end component nios_system_JTAG_UART;

	component nios_system_SDRAM is
		port (
			clk            : in    std_logic                     := 'X';             -- clk
			reset_n        : in    std_logic                     := 'X';             -- reset_n
			az_addr        : in    std_logic_vector(23 downto 0) := (others => 'X'); -- address
			az_be_n        : in    std_logic_vector(1 downto 0)  := (others => 'X'); -- byteenable_n
			az_cs          : in    std_logic                     := 'X';             -- chipselect
			az_data        : in    std_logic_vector(15 downto 0) := (others => 'X'); -- writedata
			az_rd_n        : in    std_logic                     := 'X';             -- read_n
			az_wr_n        : in    std_logic                     := 'X';             -- write_n
			za_data        : out   std_logic_vector(15 downto 0);                    -- readdata
			za_valid       : out   std_logic;                                        -- readdatavalid
			za_waitrequest : out   std_logic;                                        -- waitrequest
			zs_addr        : out   std_logic_vector(12 downto 0);                    -- export
			zs_ba          : out   std_logic_vector(1 downto 0);                     -- export
			zs_cas_n       : out   std_logic;                                        -- export
			zs_cke         : out   std_logic;                                        -- export
			zs_cs_n        : out   std_logic;                                        -- export
			zs_dq          : inout std_logic_vector(15 downto 0) := (others => 'X'); -- export
			zs_dqm         : out   std_logic_vector(1 downto 0);                     -- export
			zs_ras_n       : out   std_logic;                                        -- export
			zs_we_n        : out   std_logic                                         -- export
		);
	end component nios_system_SDRAM;

	component pwm_avalon_interface is
		port (
			read       : in  std_logic                     := 'X';             -- read
			write      : in  std_logic                     := 'X';             -- write
			chipselect : in  std_logic                     := 'X';             -- chipselect
			readdata   : out std_logic_vector(31 downto 0);                    -- readdata
			writedata  : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			byteenable : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- byteenable
			clock      : in  std_logic                     := 'X';             -- clk
			resetn     : in  std_logic                     := 'X';             -- reset_n
			Q_export   : out std_logic_vector(3 downto 0)                      -- export
		);
	end component pwm_avalon_interface;

	component nios_system_mm_interconnect_0 is
		port (
			clk_0_clk_clk                                    : in  std_logic                     := 'X';             -- clk
			CPU_reset_n_reset_bridge_in_reset_reset          : in  std_logic                     := 'X';             -- reset
			CPU_data_master_address                          : in  std_logic_vector(26 downto 0) := (others => 'X'); -- address
			CPU_data_master_waitrequest                      : out std_logic;                                        -- waitrequest
			CPU_data_master_byteenable                       : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- byteenable
			CPU_data_master_read                             : in  std_logic                     := 'X';             -- read
			CPU_data_master_readdata                         : out std_logic_vector(31 downto 0);                    -- readdata
			CPU_data_master_write                            : in  std_logic                     := 'X';             -- write
			CPU_data_master_writedata                        : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			CPU_data_master_debugaccess                      : in  std_logic                     := 'X';             -- debugaccess
			CPU_instruction_master_address                   : in  std_logic_vector(26 downto 0) := (others => 'X'); -- address
			CPU_instruction_master_waitrequest               : out std_logic;                                        -- waitrequest
			CPU_instruction_master_read                      : in  std_logic                     := 'X';             -- read
			CPU_instruction_master_readdata                  : out std_logic_vector(31 downto 0);                    -- readdata
			CPU_jtag_debug_module_address                    : out std_logic_vector(8 downto 0);                     -- address
			CPU_jtag_debug_module_write                      : out std_logic;                                        -- write
			CPU_jtag_debug_module_read                       : out std_logic;                                        -- read
			CPU_jtag_debug_module_readdata                   : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			CPU_jtag_debug_module_writedata                  : out std_logic_vector(31 downto 0);                    -- writedata
			CPU_jtag_debug_module_byteenable                 : out std_logic_vector(3 downto 0);                     -- byteenable
			CPU_jtag_debug_module_waitrequest                : in  std_logic                     := 'X';             -- waitrequest
			CPU_jtag_debug_module_debugaccess                : out std_logic;                                        -- debugaccess
			INPUT_s1_address                                 : out std_logic_vector(1 downto 0);                     -- address
			INPUT_s1_readdata                                : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			JTAG_UART_avalon_jtag_slave_address              : out std_logic_vector(0 downto 0);                     -- address
			JTAG_UART_avalon_jtag_slave_write                : out std_logic;                                        -- write
			JTAG_UART_avalon_jtag_slave_read                 : out std_logic;                                        -- read
			JTAG_UART_avalon_jtag_slave_readdata             : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			JTAG_UART_avalon_jtag_slave_writedata            : out std_logic_vector(31 downto 0);                    -- writedata
			JTAG_UART_avalon_jtag_slave_waitrequest          : in  std_logic                     := 'X';             -- waitrequest
			JTAG_UART_avalon_jtag_slave_chipselect           : out std_logic;                                        -- chipselect
			MEMOIRE_INTERNE_s1_address                       : out std_logic_vector(9 downto 0);                     -- address
			MEMOIRE_INTERNE_s1_write                         : out std_logic;                                        -- write
			MEMOIRE_INTERNE_s1_readdata                      : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			MEMOIRE_INTERNE_s1_writedata                     : out std_logic_vector(31 downto 0);                    -- writedata
			MEMOIRE_INTERNE_s1_byteenable                    : out std_logic_vector(3 downto 0);                     -- byteenable
			MEMOIRE_INTERNE_s1_chipselect                    : out std_logic;                                        -- chipselect
			MEMOIRE_INTERNE_s1_clken                         : out std_logic;                                        -- clken
			OUTPUT_s1_address                                : out std_logic_vector(1 downto 0);                     -- address
			OUTPUT_s1_write                                  : out std_logic;                                        -- write
			OUTPUT_s1_readdata                               : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			OUTPUT_s1_writedata                              : out std_logic_vector(31 downto 0);                    -- writedata
			OUTPUT_s1_chipselect                             : out std_logic;                                        -- chipselect
			pwm_avalon_interface_1_avalon_slave_0_write      : out std_logic;                                        -- write
			pwm_avalon_interface_1_avalon_slave_0_read       : out std_logic;                                        -- read
			pwm_avalon_interface_1_avalon_slave_0_readdata   : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			pwm_avalon_interface_1_avalon_slave_0_writedata  : out std_logic_vector(31 downto 0);                    -- writedata
			pwm_avalon_interface_1_avalon_slave_0_byteenable : out std_logic_vector(3 downto 0);                     -- byteenable
			pwm_avalon_interface_1_avalon_slave_0_chipselect : out std_logic;                                        -- chipselect
			SDRAM_s1_address                                 : out std_logic_vector(23 downto 0);                    -- address
			SDRAM_s1_write                                   : out std_logic;                                        -- write
			SDRAM_s1_read                                    : out std_logic;                                        -- read
			SDRAM_s1_readdata                                : in  std_logic_vector(15 downto 0) := (others => 'X'); -- readdata
			SDRAM_s1_writedata                               : out std_logic_vector(15 downto 0);                    -- writedata
			SDRAM_s1_byteenable                              : out std_logic_vector(1 downto 0);                     -- byteenable
			SDRAM_s1_readdatavalid                           : in  std_logic                     := 'X';             -- readdatavalid
			SDRAM_s1_waitrequest                             : in  std_logic                     := 'X';             -- waitrequest
			SDRAM_s1_chipselect                              : out std_logic                                         -- chipselect
		);
	end component nios_system_mm_interconnect_0;

	component nios_system_irq_mapper is
		port (
			clk           : in  std_logic                     := 'X'; -- clk
			reset         : in  std_logic                     := 'X'; -- reset
			receiver0_irq : in  std_logic                     := 'X'; -- irq
			sender_irq    : out std_logic_vector(31 downto 0)         -- irq
		);
	end component nios_system_irq_mapper;

	component altera_reset_controller is
		generic (
			NUM_RESET_INPUTS          : integer := 6;
			OUTPUT_RESET_SYNC_EDGES   : string  := "deassert";
			SYNC_DEPTH                : integer := 2;
			RESET_REQUEST_PRESENT     : integer := 0;
			RESET_REQ_WAIT_TIME       : integer := 1;
			MIN_RST_ASSERTION_TIME    : integer := 3;
			RESET_REQ_EARLY_DSRT_TIME : integer := 1;
			USE_RESET_REQUEST_IN0     : integer := 0;
			USE_RESET_REQUEST_IN1     : integer := 0;
			USE_RESET_REQUEST_IN2     : integer := 0;
			USE_RESET_REQUEST_IN3     : integer := 0;
			USE_RESET_REQUEST_IN4     : integer := 0;
			USE_RESET_REQUEST_IN5     : integer := 0;
			USE_RESET_REQUEST_IN6     : integer := 0;
			USE_RESET_REQUEST_IN7     : integer := 0;
			USE_RESET_REQUEST_IN8     : integer := 0;
			USE_RESET_REQUEST_IN9     : integer := 0;
			USE_RESET_REQUEST_IN10    : integer := 0;
			USE_RESET_REQUEST_IN11    : integer := 0;
			USE_RESET_REQUEST_IN12    : integer := 0;
			USE_RESET_REQUEST_IN13    : integer := 0;
			USE_RESET_REQUEST_IN14    : integer := 0;
			USE_RESET_REQUEST_IN15    : integer := 0;
			ADAPT_RESET_REQUEST       : integer := 0
		);
		port (
			reset_in0      : in  std_logic := 'X'; -- reset
			reset_in1      : in  std_logic := 'X'; -- reset
			clk            : in  std_logic := 'X'; -- clk
			reset_out      : out std_logic;        -- reset
			reset_req      : out std_logic;        -- reset_req
			reset_req_in0  : in  std_logic := 'X'; -- reset_req
			reset_req_in1  : in  std_logic := 'X'; -- reset_req
			reset_in2      : in  std_logic := 'X'; -- reset
			reset_req_in2  : in  std_logic := 'X'; -- reset_req
			reset_in3      : in  std_logic := 'X'; -- reset
			reset_req_in3  : in  std_logic := 'X'; -- reset_req
			reset_in4      : in  std_logic := 'X'; -- reset
			reset_req_in4  : in  std_logic := 'X'; -- reset_req
			reset_in5      : in  std_logic := 'X'; -- reset
			reset_req_in5  : in  std_logic := 'X'; -- reset_req
			reset_in6      : in  std_logic := 'X'; -- reset
			reset_req_in6  : in  std_logic := 'X'; -- reset_req
			reset_in7      : in  std_logic := 'X'; -- reset
			reset_req_in7  : in  std_logic := 'X'; -- reset_req
			reset_in8      : in  std_logic := 'X'; -- reset
			reset_req_in8  : in  std_logic := 'X'; -- reset_req
			reset_in9      : in  std_logic := 'X'; -- reset
			reset_req_in9  : in  std_logic := 'X'; -- reset_req
			reset_in10     : in  std_logic := 'X'; -- reset
			reset_req_in10 : in  std_logic := 'X'; -- reset_req
			reset_in11     : in  std_logic := 'X'; -- reset
			reset_req_in11 : in  std_logic := 'X'; -- reset_req
			reset_in12     : in  std_logic := 'X'; -- reset
			reset_req_in12 : in  std_logic := 'X'; -- reset_req
			reset_in13     : in  std_logic := 'X'; -- reset
			reset_req_in13 : in  std_logic := 'X'; -- reset_req
			reset_in14     : in  std_logic := 'X'; -- reset
			reset_req_in14 : in  std_logic := 'X'; -- reset_req
			reset_in15     : in  std_logic := 'X'; -- reset
			reset_req_in15 : in  std_logic := 'X'  -- reset_req
		);
	end component altera_reset_controller;

	signal mm_interconnect_0_input_s1_address                                 : std_logic_vector(1 downto 0);  -- mm_interconnect_0:INPUT_s1_address -> INPUT:address
	signal mm_interconnect_0_input_s1_readdata                                : std_logic_vector(31 downto 0); -- INPUT:readdata -> mm_interconnect_0:INPUT_s1_readdata
	signal cpu_data_master_waitrequest                                        : std_logic;                     -- mm_interconnect_0:CPU_data_master_waitrequest -> CPU:d_waitrequest
	signal cpu_data_master_writedata                                          : std_logic_vector(31 downto 0); -- CPU:d_writedata -> mm_interconnect_0:CPU_data_master_writedata
	signal cpu_data_master_address                                            : std_logic_vector(26 downto 0); -- CPU:d_address -> mm_interconnect_0:CPU_data_master_address
	signal cpu_data_master_write                                              : std_logic;                     -- CPU:d_write -> mm_interconnect_0:CPU_data_master_write
	signal cpu_data_master_read                                               : std_logic;                     -- CPU:d_read -> mm_interconnect_0:CPU_data_master_read
	signal cpu_data_master_readdata                                           : std_logic_vector(31 downto 0); -- mm_interconnect_0:CPU_data_master_readdata -> CPU:d_readdata
	signal cpu_data_master_debugaccess                                        : std_logic;                     -- CPU:jtag_debug_module_debugaccess_to_roms -> mm_interconnect_0:CPU_data_master_debugaccess
	signal cpu_data_master_byteenable                                         : std_logic_vector(3 downto 0);  -- CPU:d_byteenable -> mm_interconnect_0:CPU_data_master_byteenable
	signal cpu_instruction_master_waitrequest                                 : std_logic;                     -- mm_interconnect_0:CPU_instruction_master_waitrequest -> CPU:i_waitrequest
	signal cpu_instruction_master_address                                     : std_logic_vector(26 downto 0); -- CPU:i_address -> mm_interconnect_0:CPU_instruction_master_address
	signal cpu_instruction_master_read                                        : std_logic;                     -- CPU:i_read -> mm_interconnect_0:CPU_instruction_master_read
	signal cpu_instruction_master_readdata                                    : std_logic_vector(31 downto 0); -- mm_interconnect_0:CPU_instruction_master_readdata -> CPU:i_readdata
	signal mm_interconnect_0_memoire_interne_s1_writedata                     : std_logic_vector(31 downto 0); -- mm_interconnect_0:MEMOIRE_INTERNE_s1_writedata -> MEMOIRE_INTERNE:writedata
	signal mm_interconnect_0_memoire_interne_s1_address                       : std_logic_vector(9 downto 0);  -- mm_interconnect_0:MEMOIRE_INTERNE_s1_address -> MEMOIRE_INTERNE:address
	signal mm_interconnect_0_memoire_interne_s1_chipselect                    : std_logic;                     -- mm_interconnect_0:MEMOIRE_INTERNE_s1_chipselect -> MEMOIRE_INTERNE:chipselect
	signal mm_interconnect_0_memoire_interne_s1_clken                         : std_logic;                     -- mm_interconnect_0:MEMOIRE_INTERNE_s1_clken -> MEMOIRE_INTERNE:clken
	signal mm_interconnect_0_memoire_interne_s1_write                         : std_logic;                     -- mm_interconnect_0:MEMOIRE_INTERNE_s1_write -> MEMOIRE_INTERNE:write
	signal mm_interconnect_0_memoire_interne_s1_readdata                      : std_logic_vector(31 downto 0); -- MEMOIRE_INTERNE:readdata -> mm_interconnect_0:MEMOIRE_INTERNE_s1_readdata
	signal mm_interconnect_0_memoire_interne_s1_byteenable                    : std_logic_vector(3 downto 0);  -- mm_interconnect_0:MEMOIRE_INTERNE_s1_byteenable -> MEMOIRE_INTERNE:byteenable
	signal mm_interconnect_0_pwm_avalon_interface_1_avalon_slave_0_writedata  : std_logic_vector(31 downto 0); -- mm_interconnect_0:pwm_avalon_interface_1_avalon_slave_0_writedata -> pwm_avalon_interface_1:writedata
	signal mm_interconnect_0_pwm_avalon_interface_1_avalon_slave_0_chipselect : std_logic;                     -- mm_interconnect_0:pwm_avalon_interface_1_avalon_slave_0_chipselect -> pwm_avalon_interface_1:chipselect
	signal mm_interconnect_0_pwm_avalon_interface_1_avalon_slave_0_write      : std_logic;                     -- mm_interconnect_0:pwm_avalon_interface_1_avalon_slave_0_write -> pwm_avalon_interface_1:write
	signal mm_interconnect_0_pwm_avalon_interface_1_avalon_slave_0_read       : std_logic;                     -- mm_interconnect_0:pwm_avalon_interface_1_avalon_slave_0_read -> pwm_avalon_interface_1:read
	signal mm_interconnect_0_pwm_avalon_interface_1_avalon_slave_0_readdata   : std_logic_vector(31 downto 0); -- pwm_avalon_interface_1:readdata -> mm_interconnect_0:pwm_avalon_interface_1_avalon_slave_0_readdata
	signal mm_interconnect_0_pwm_avalon_interface_1_avalon_slave_0_byteenable : std_logic_vector(3 downto 0);  -- mm_interconnect_0:pwm_avalon_interface_1_avalon_slave_0_byteenable -> pwm_avalon_interface_1:byteenable
	signal mm_interconnect_0_output_s1_writedata                              : std_logic_vector(31 downto 0); -- mm_interconnect_0:OUTPUT_s1_writedata -> OUTPUT:writedata
	signal mm_interconnect_0_output_s1_address                                : std_logic_vector(1 downto 0);  -- mm_interconnect_0:OUTPUT_s1_address -> OUTPUT:address
	signal mm_interconnect_0_output_s1_chipselect                             : std_logic;                     -- mm_interconnect_0:OUTPUT_s1_chipselect -> OUTPUT:chipselect
	signal mm_interconnect_0_output_s1_write                                  : std_logic;                     -- mm_interconnect_0:OUTPUT_s1_write -> mm_interconnect_0_output_s1_write:in
	signal mm_interconnect_0_output_s1_readdata                               : std_logic_vector(31 downto 0); -- OUTPUT:readdata -> mm_interconnect_0:OUTPUT_s1_readdata
	signal mm_interconnect_0_cpu_jtag_debug_module_waitrequest                : std_logic;                     -- CPU:jtag_debug_module_waitrequest -> mm_interconnect_0:CPU_jtag_debug_module_waitrequest
	signal mm_interconnect_0_cpu_jtag_debug_module_writedata                  : std_logic_vector(31 downto 0); -- mm_interconnect_0:CPU_jtag_debug_module_writedata -> CPU:jtag_debug_module_writedata
	signal mm_interconnect_0_cpu_jtag_debug_module_address                    : std_logic_vector(8 downto 0);  -- mm_interconnect_0:CPU_jtag_debug_module_address -> CPU:jtag_debug_module_address
	signal mm_interconnect_0_cpu_jtag_debug_module_write                      : std_logic;                     -- mm_interconnect_0:CPU_jtag_debug_module_write -> CPU:jtag_debug_module_write
	signal mm_interconnect_0_cpu_jtag_debug_module_read                       : std_logic;                     -- mm_interconnect_0:CPU_jtag_debug_module_read -> CPU:jtag_debug_module_read
	signal mm_interconnect_0_cpu_jtag_debug_module_readdata                   : std_logic_vector(31 downto 0); -- CPU:jtag_debug_module_readdata -> mm_interconnect_0:CPU_jtag_debug_module_readdata
	signal mm_interconnect_0_cpu_jtag_debug_module_debugaccess                : std_logic;                     -- mm_interconnect_0:CPU_jtag_debug_module_debugaccess -> CPU:jtag_debug_module_debugaccess
	signal mm_interconnect_0_cpu_jtag_debug_module_byteenable                 : std_logic_vector(3 downto 0);  -- mm_interconnect_0:CPU_jtag_debug_module_byteenable -> CPU:jtag_debug_module_byteenable
	signal mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest          : std_logic;                     -- JTAG_UART:av_waitrequest -> mm_interconnect_0:JTAG_UART_avalon_jtag_slave_waitrequest
	signal mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata            : std_logic_vector(31 downto 0); -- mm_interconnect_0:JTAG_UART_avalon_jtag_slave_writedata -> JTAG_UART:av_writedata
	signal mm_interconnect_0_jtag_uart_avalon_jtag_slave_address              : std_logic_vector(0 downto 0);  -- mm_interconnect_0:JTAG_UART_avalon_jtag_slave_address -> JTAG_UART:av_address
	signal mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect           : std_logic;                     -- mm_interconnect_0:JTAG_UART_avalon_jtag_slave_chipselect -> JTAG_UART:av_chipselect
	signal mm_interconnect_0_jtag_uart_avalon_jtag_slave_write                : std_logic;                     -- mm_interconnect_0:JTAG_UART_avalon_jtag_slave_write -> mm_interconnect_0_jtag_uart_avalon_jtag_slave_write:in
	signal mm_interconnect_0_jtag_uart_avalon_jtag_slave_read                 : std_logic;                     -- mm_interconnect_0:JTAG_UART_avalon_jtag_slave_read -> mm_interconnect_0_jtag_uart_avalon_jtag_slave_read:in
	signal mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata             : std_logic_vector(31 downto 0); -- JTAG_UART:av_readdata -> mm_interconnect_0:JTAG_UART_avalon_jtag_slave_readdata
	signal mm_interconnect_0_sdram_s1_waitrequest                             : std_logic;                     -- SDRAM:za_waitrequest -> mm_interconnect_0:SDRAM_s1_waitrequest
	signal mm_interconnect_0_sdram_s1_writedata                               : std_logic_vector(15 downto 0); -- mm_interconnect_0:SDRAM_s1_writedata -> SDRAM:az_data
	signal mm_interconnect_0_sdram_s1_address                                 : std_logic_vector(23 downto 0); -- mm_interconnect_0:SDRAM_s1_address -> SDRAM:az_addr
	signal mm_interconnect_0_sdram_s1_chipselect                              : std_logic;                     -- mm_interconnect_0:SDRAM_s1_chipselect -> SDRAM:az_cs
	signal mm_interconnect_0_sdram_s1_write                                   : std_logic;                     -- mm_interconnect_0:SDRAM_s1_write -> mm_interconnect_0_sdram_s1_write:in
	signal mm_interconnect_0_sdram_s1_read                                    : std_logic;                     -- mm_interconnect_0:SDRAM_s1_read -> mm_interconnect_0_sdram_s1_read:in
	signal mm_interconnect_0_sdram_s1_readdata                                : std_logic_vector(15 downto 0); -- SDRAM:za_data -> mm_interconnect_0:SDRAM_s1_readdata
	signal mm_interconnect_0_sdram_s1_readdatavalid                           : std_logic;                     -- SDRAM:za_valid -> mm_interconnect_0:SDRAM_s1_readdatavalid
	signal mm_interconnect_0_sdram_s1_byteenable                              : std_logic_vector(1 downto 0);  -- mm_interconnect_0:SDRAM_s1_byteenable -> mm_interconnect_0_sdram_s1_byteenable:in
	signal irq_mapper_receiver0_irq                                           : std_logic;                     -- JTAG_UART:av_irq -> irq_mapper:receiver0_irq
	signal cpu_d_irq_irq                                                      : std_logic_vector(31 downto 0); -- irq_mapper:sender_irq -> CPU:d_irq
	signal rst_controller_reset_out_reset                                     : std_logic;                     -- rst_controller:reset_out -> [MEMOIRE_INTERNE:reset, irq_mapper:reset, mm_interconnect_0:CPU_reset_n_reset_bridge_in_reset_reset, rst_controller_reset_out_reset:in, rst_translator:in_reset]
	signal rst_controller_reset_out_reset_req                                 : std_logic;                     -- rst_controller:reset_req -> [CPU:reset_req, MEMOIRE_INTERNE:reset_req, rst_translator:reset_req_in]
	signal cpu_jtag_debug_module_reset_reset                                  : std_logic;                     -- CPU:jtag_debug_module_resetrequest -> rst_controller:reset_in1
	signal reset_reset_n_ports_inv                                            : std_logic;                     -- reset_reset_n:inv -> rst_controller:reset_in0
	signal mm_interconnect_0_output_s1_write_ports_inv                        : std_logic;                     -- mm_interconnect_0_output_s1_write:inv -> OUTPUT:write_n
	signal mm_interconnect_0_jtag_uart_avalon_jtag_slave_write_ports_inv      : std_logic;                     -- mm_interconnect_0_jtag_uart_avalon_jtag_slave_write:inv -> JTAG_UART:av_write_n
	signal mm_interconnect_0_jtag_uart_avalon_jtag_slave_read_ports_inv       : std_logic;                     -- mm_interconnect_0_jtag_uart_avalon_jtag_slave_read:inv -> JTAG_UART:av_read_n
	signal mm_interconnect_0_sdram_s1_write_ports_inv                         : std_logic;                     -- mm_interconnect_0_sdram_s1_write:inv -> SDRAM:az_wr_n
	signal mm_interconnect_0_sdram_s1_read_ports_inv                          : std_logic;                     -- mm_interconnect_0_sdram_s1_read:inv -> SDRAM:az_rd_n
	signal mm_interconnect_0_sdram_s1_byteenable_ports_inv                    : std_logic_vector(1 downto 0);  -- mm_interconnect_0_sdram_s1_byteenable:inv -> SDRAM:az_be_n
	signal rst_controller_reset_out_reset_ports_inv                           : std_logic;                     -- rst_controller_reset_out_reset:inv -> [CPU:reset_n, INPUT:reset_n, JTAG_UART:rst_n, OUTPUT:reset_n, SDRAM:reset_n, pwm_avalon_interface_1:resetn]

begin

	cpu : component nios_system_CPU
		port map (
			clk                                   => clk_clk,                                             --                       clk.clk
			reset_n                               => rst_controller_reset_out_reset_ports_inv,            --                   reset_n.reset_n
			reset_req                             => rst_controller_reset_out_reset_req,                  --                          .reset_req
			d_address                             => cpu_data_master_address,                             --               data_master.address
			d_byteenable                          => cpu_data_master_byteenable,                          --                          .byteenable
			d_read                                => cpu_data_master_read,                                --                          .read
			d_readdata                            => cpu_data_master_readdata,                            --                          .readdata
			d_waitrequest                         => cpu_data_master_waitrequest,                         --                          .waitrequest
			d_write                               => cpu_data_master_write,                               --                          .write
			d_writedata                           => cpu_data_master_writedata,                           --                          .writedata
			jtag_debug_module_debugaccess_to_roms => cpu_data_master_debugaccess,                         --                          .debugaccess
			i_address                             => cpu_instruction_master_address,                      --        instruction_master.address
			i_read                                => cpu_instruction_master_read,                         --                          .read
			i_readdata                            => cpu_instruction_master_readdata,                     --                          .readdata
			i_waitrequest                         => cpu_instruction_master_waitrequest,                  --                          .waitrequest
			d_irq                                 => cpu_d_irq_irq,                                       --                     d_irq.irq
			jtag_debug_module_resetrequest        => cpu_jtag_debug_module_reset_reset,                   --   jtag_debug_module_reset.reset
			jtag_debug_module_address             => mm_interconnect_0_cpu_jtag_debug_module_address,     --         jtag_debug_module.address
			jtag_debug_module_byteenable          => mm_interconnect_0_cpu_jtag_debug_module_byteenable,  --                          .byteenable
			jtag_debug_module_debugaccess         => mm_interconnect_0_cpu_jtag_debug_module_debugaccess, --                          .debugaccess
			jtag_debug_module_read                => mm_interconnect_0_cpu_jtag_debug_module_read,        --                          .read
			jtag_debug_module_readdata            => mm_interconnect_0_cpu_jtag_debug_module_readdata,    --                          .readdata
			jtag_debug_module_waitrequest         => mm_interconnect_0_cpu_jtag_debug_module_waitrequest, --                          .waitrequest
			jtag_debug_module_write               => mm_interconnect_0_cpu_jtag_debug_module_write,       --                          .write
			jtag_debug_module_writedata           => mm_interconnect_0_cpu_jtag_debug_module_writedata,   --                          .writedata
			no_ci_readra                          => open                                                 -- custom_instruction_master.readra
		);

	memoire_interne : component nios_system_MEMOIRE_INTERNE
		port map (
			clk        => clk_clk,                                         --   clk1.clk
			address    => mm_interconnect_0_memoire_interne_s1_address,    --     s1.address
			clken      => mm_interconnect_0_memoire_interne_s1_clken,      --       .clken
			chipselect => mm_interconnect_0_memoire_interne_s1_chipselect, --       .chipselect
			write      => mm_interconnect_0_memoire_interne_s1_write,      --       .write
			readdata   => mm_interconnect_0_memoire_interne_s1_readdata,   --       .readdata
			writedata  => mm_interconnect_0_memoire_interne_s1_writedata,  --       .writedata
			byteenable => mm_interconnect_0_memoire_interne_s1_byteenable, --       .byteenable
			reset      => rst_controller_reset_out_reset,                  -- reset1.reset
			reset_req  => rst_controller_reset_out_reset_req               --       .reset_req
		);

	input : component nios_system_INPUT
		port map (
			clk      => clk_clk,                                  --                 clk.clk
			reset_n  => rst_controller_reset_out_reset_ports_inv, --               reset.reset_n
			address  => mm_interconnect_0_input_s1_address,       --                  s1.address
			readdata => mm_interconnect_0_input_s1_readdata,      --                    .readdata
			in_port  => switches_export                           -- external_connection.export
		);

	output : component nios_system_OUTPUT
		port map (
			clk        => clk_clk,                                     --                 clk.clk
			reset_n    => rst_controller_reset_out_reset_ports_inv,    --               reset.reset_n
			address    => mm_interconnect_0_output_s1_address,         --                  s1.address
			write_n    => mm_interconnect_0_output_s1_write_ports_inv, --                    .write_n
			writedata  => mm_interconnect_0_output_s1_writedata,       --                    .writedata
			chipselect => mm_interconnect_0_output_s1_chipselect,      --                    .chipselect
			readdata   => mm_interconnect_0_output_s1_readdata,        --                    .readdata
			out_port   => leds_export                                  -- external_connection.export
		);

	jtag_uart : component nios_system_JTAG_UART
		port map (
			clk            => clk_clk,                                                       --               clk.clk
			rst_n          => rst_controller_reset_out_reset_ports_inv,                      --             reset.reset_n
			av_chipselect  => mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect,      -- avalon_jtag_slave.chipselect
			av_address     => mm_interconnect_0_jtag_uart_avalon_jtag_slave_address(0),      --                  .address
			av_read_n      => mm_interconnect_0_jtag_uart_avalon_jtag_slave_read_ports_inv,  --                  .read_n
			av_readdata    => mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata,        --                  .readdata
			av_write_n     => mm_interconnect_0_jtag_uart_avalon_jtag_slave_write_ports_inv, --                  .write_n
			av_writedata   => mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata,       --                  .writedata
			av_waitrequest => mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest,     --                  .waitrequest
			av_irq         => irq_mapper_receiver0_irq                                       --               irq.irq
		);

	sdram : component nios_system_SDRAM
		port map (
			clk            => clk_clk,                                         --   clk.clk
			reset_n        => rst_controller_reset_out_reset_ports_inv,        -- reset.reset_n
			az_addr        => mm_interconnect_0_sdram_s1_address,              --    s1.address
			az_be_n        => mm_interconnect_0_sdram_s1_byteenable_ports_inv, --      .byteenable_n
			az_cs          => mm_interconnect_0_sdram_s1_chipselect,           --      .chipselect
			az_data        => mm_interconnect_0_sdram_s1_writedata,            --      .writedata
			az_rd_n        => mm_interconnect_0_sdram_s1_read_ports_inv,       --      .read_n
			az_wr_n        => mm_interconnect_0_sdram_s1_write_ports_inv,      --      .write_n
			za_data        => mm_interconnect_0_sdram_s1_readdata,             --      .readdata
			za_valid       => mm_interconnect_0_sdram_s1_readdatavalid,        --      .readdatavalid
			za_waitrequest => mm_interconnect_0_sdram_s1_waitrequest,          --      .waitrequest
			zs_addr        => sdram_wire_addr,                                 --  wire.export
			zs_ba          => sdram_wire_ba,                                   --      .export
			zs_cas_n       => sdram_wire_cas_n,                                --      .export
			zs_cke         => sdram_wire_cke,                                  --      .export
			zs_cs_n        => sdram_wire_cs_n,                                 --      .export
			zs_dq          => sdram_wire_dq,                                   --      .export
			zs_dqm         => sdram_wire_dqm,                                  --      .export
			zs_ras_n       => sdram_wire_ras_n,                                --      .export
			zs_we_n        => sdram_wire_we_n                                  --      .export
		);

	pwm_avalon_interface_1 : component pwm_avalon_interface
		port map (
			read       => mm_interconnect_0_pwm_avalon_interface_1_avalon_slave_0_read,       -- avalon_slave_0.read
			write      => mm_interconnect_0_pwm_avalon_interface_1_avalon_slave_0_write,      --               .write
			chipselect => mm_interconnect_0_pwm_avalon_interface_1_avalon_slave_0_chipselect, --               .chipselect
			readdata   => mm_interconnect_0_pwm_avalon_interface_1_avalon_slave_0_readdata,   --               .readdata
			writedata  => mm_interconnect_0_pwm_avalon_interface_1_avalon_slave_0_writedata,  --               .writedata
			byteenable => mm_interconnect_0_pwm_avalon_interface_1_avalon_slave_0_byteenable, --               .byteenable
			clock      => clk_clk,                                                            --     clock_sink.clk
			resetn     => rst_controller_reset_out_reset_ports_inv,                           --     reset_sink.reset_n
			Q_export   => pwm_avalon_interface_export                                         --    conduit_end.export
		);

	mm_interconnect_0 : component nios_system_mm_interconnect_0
		port map (
			clk_0_clk_clk                                    => clk_clk,                                                            --                             clk_0_clk.clk
			CPU_reset_n_reset_bridge_in_reset_reset          => rst_controller_reset_out_reset,                                     --     CPU_reset_n_reset_bridge_in_reset.reset
			CPU_data_master_address                          => cpu_data_master_address,                                            --                       CPU_data_master.address
			CPU_data_master_waitrequest                      => cpu_data_master_waitrequest,                                        --                                      .waitrequest
			CPU_data_master_byteenable                       => cpu_data_master_byteenable,                                         --                                      .byteenable
			CPU_data_master_read                             => cpu_data_master_read,                                               --                                      .read
			CPU_data_master_readdata                         => cpu_data_master_readdata,                                           --                                      .readdata
			CPU_data_master_write                            => cpu_data_master_write,                                              --                                      .write
			CPU_data_master_writedata                        => cpu_data_master_writedata,                                          --                                      .writedata
			CPU_data_master_debugaccess                      => cpu_data_master_debugaccess,                                        --                                      .debugaccess
			CPU_instruction_master_address                   => cpu_instruction_master_address,                                     --                CPU_instruction_master.address
			CPU_instruction_master_waitrequest               => cpu_instruction_master_waitrequest,                                 --                                      .waitrequest
			CPU_instruction_master_read                      => cpu_instruction_master_read,                                        --                                      .read
			CPU_instruction_master_readdata                  => cpu_instruction_master_readdata,                                    --                                      .readdata
			CPU_jtag_debug_module_address                    => mm_interconnect_0_cpu_jtag_debug_module_address,                    --                 CPU_jtag_debug_module.address
			CPU_jtag_debug_module_write                      => mm_interconnect_0_cpu_jtag_debug_module_write,                      --                                      .write
			CPU_jtag_debug_module_read                       => mm_interconnect_0_cpu_jtag_debug_module_read,                       --                                      .read
			CPU_jtag_debug_module_readdata                   => mm_interconnect_0_cpu_jtag_debug_module_readdata,                   --                                      .readdata
			CPU_jtag_debug_module_writedata                  => mm_interconnect_0_cpu_jtag_debug_module_writedata,                  --                                      .writedata
			CPU_jtag_debug_module_byteenable                 => mm_interconnect_0_cpu_jtag_debug_module_byteenable,                 --                                      .byteenable
			CPU_jtag_debug_module_waitrequest                => mm_interconnect_0_cpu_jtag_debug_module_waitrequest,                --                                      .waitrequest
			CPU_jtag_debug_module_debugaccess                => mm_interconnect_0_cpu_jtag_debug_module_debugaccess,                --                                      .debugaccess
			INPUT_s1_address                                 => mm_interconnect_0_input_s1_address,                                 --                              INPUT_s1.address
			INPUT_s1_readdata                                => mm_interconnect_0_input_s1_readdata,                                --                                      .readdata
			JTAG_UART_avalon_jtag_slave_address              => mm_interconnect_0_jtag_uart_avalon_jtag_slave_address,              --           JTAG_UART_avalon_jtag_slave.address
			JTAG_UART_avalon_jtag_slave_write                => mm_interconnect_0_jtag_uart_avalon_jtag_slave_write,                --                                      .write
			JTAG_UART_avalon_jtag_slave_read                 => mm_interconnect_0_jtag_uart_avalon_jtag_slave_read,                 --                                      .read
			JTAG_UART_avalon_jtag_slave_readdata             => mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata,             --                                      .readdata
			JTAG_UART_avalon_jtag_slave_writedata            => mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata,            --                                      .writedata
			JTAG_UART_avalon_jtag_slave_waitrequest          => mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest,          --                                      .waitrequest
			JTAG_UART_avalon_jtag_slave_chipselect           => mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect,           --                                      .chipselect
			MEMOIRE_INTERNE_s1_address                       => mm_interconnect_0_memoire_interne_s1_address,                       --                    MEMOIRE_INTERNE_s1.address
			MEMOIRE_INTERNE_s1_write                         => mm_interconnect_0_memoire_interne_s1_write,                         --                                      .write
			MEMOIRE_INTERNE_s1_readdata                      => mm_interconnect_0_memoire_interne_s1_readdata,                      --                                      .readdata
			MEMOIRE_INTERNE_s1_writedata                     => mm_interconnect_0_memoire_interne_s1_writedata,                     --                                      .writedata
			MEMOIRE_INTERNE_s1_byteenable                    => mm_interconnect_0_memoire_interne_s1_byteenable,                    --                                      .byteenable
			MEMOIRE_INTERNE_s1_chipselect                    => mm_interconnect_0_memoire_interne_s1_chipselect,                    --                                      .chipselect
			MEMOIRE_INTERNE_s1_clken                         => mm_interconnect_0_memoire_interne_s1_clken,                         --                                      .clken
			OUTPUT_s1_address                                => mm_interconnect_0_output_s1_address,                                --                             OUTPUT_s1.address
			OUTPUT_s1_write                                  => mm_interconnect_0_output_s1_write,                                  --                                      .write
			OUTPUT_s1_readdata                               => mm_interconnect_0_output_s1_readdata,                               --                                      .readdata
			OUTPUT_s1_writedata                              => mm_interconnect_0_output_s1_writedata,                              --                                      .writedata
			OUTPUT_s1_chipselect                             => mm_interconnect_0_output_s1_chipselect,                             --                                      .chipselect
			pwm_avalon_interface_1_avalon_slave_0_write      => mm_interconnect_0_pwm_avalon_interface_1_avalon_slave_0_write,      -- pwm_avalon_interface_1_avalon_slave_0.write
			pwm_avalon_interface_1_avalon_slave_0_read       => mm_interconnect_0_pwm_avalon_interface_1_avalon_slave_0_read,       --                                      .read
			pwm_avalon_interface_1_avalon_slave_0_readdata   => mm_interconnect_0_pwm_avalon_interface_1_avalon_slave_0_readdata,   --                                      .readdata
			pwm_avalon_interface_1_avalon_slave_0_writedata  => mm_interconnect_0_pwm_avalon_interface_1_avalon_slave_0_writedata,  --                                      .writedata
			pwm_avalon_interface_1_avalon_slave_0_byteenable => mm_interconnect_0_pwm_avalon_interface_1_avalon_slave_0_byteenable, --                                      .byteenable
			pwm_avalon_interface_1_avalon_slave_0_chipselect => mm_interconnect_0_pwm_avalon_interface_1_avalon_slave_0_chipselect, --                                      .chipselect
			SDRAM_s1_address                                 => mm_interconnect_0_sdram_s1_address,                                 --                              SDRAM_s1.address
			SDRAM_s1_write                                   => mm_interconnect_0_sdram_s1_write,                                   --                                      .write
			SDRAM_s1_read                                    => mm_interconnect_0_sdram_s1_read,                                    --                                      .read
			SDRAM_s1_readdata                                => mm_interconnect_0_sdram_s1_readdata,                                --                                      .readdata
			SDRAM_s1_writedata                               => mm_interconnect_0_sdram_s1_writedata,                               --                                      .writedata
			SDRAM_s1_byteenable                              => mm_interconnect_0_sdram_s1_byteenable,                              --                                      .byteenable
			SDRAM_s1_readdatavalid                           => mm_interconnect_0_sdram_s1_readdatavalid,                           --                                      .readdatavalid
			SDRAM_s1_waitrequest                             => mm_interconnect_0_sdram_s1_waitrequest,                             --                                      .waitrequest
			SDRAM_s1_chipselect                              => mm_interconnect_0_sdram_s1_chipselect                               --                                      .chipselect
		);

	irq_mapper : component nios_system_irq_mapper
		port map (
			clk           => clk_clk,                        --       clk.clk
			reset         => rst_controller_reset_out_reset, -- clk_reset.reset
			receiver0_irq => irq_mapper_receiver0_irq,       -- receiver0.irq
			sender_irq    => cpu_d_irq_irq                   --    sender.irq
		);

	rst_controller : component altera_reset_controller
		generic map (
			NUM_RESET_INPUTS          => 2,
			OUTPUT_RESET_SYNC_EDGES   => "deassert",
			SYNC_DEPTH                => 2,
			RESET_REQUEST_PRESENT     => 1,
			RESET_REQ_WAIT_TIME       => 1,
			MIN_RST_ASSERTION_TIME    => 3,
			RESET_REQ_EARLY_DSRT_TIME => 1,
			USE_RESET_REQUEST_IN0     => 0,
			USE_RESET_REQUEST_IN1     => 0,
			USE_RESET_REQUEST_IN2     => 0,
			USE_RESET_REQUEST_IN3     => 0,
			USE_RESET_REQUEST_IN4     => 0,
			USE_RESET_REQUEST_IN5     => 0,
			USE_RESET_REQUEST_IN6     => 0,
			USE_RESET_REQUEST_IN7     => 0,
			USE_RESET_REQUEST_IN8     => 0,
			USE_RESET_REQUEST_IN9     => 0,
			USE_RESET_REQUEST_IN10    => 0,
			USE_RESET_REQUEST_IN11    => 0,
			USE_RESET_REQUEST_IN12    => 0,
			USE_RESET_REQUEST_IN13    => 0,
			USE_RESET_REQUEST_IN14    => 0,
			USE_RESET_REQUEST_IN15    => 0,
			ADAPT_RESET_REQUEST       => 0
		)
		port map (
			reset_in0      => reset_reset_n_ports_inv,            -- reset_in0.reset
			reset_in1      => cpu_jtag_debug_module_reset_reset,  -- reset_in1.reset
			clk            => clk_clk,                            --       clk.clk
			reset_out      => rst_controller_reset_out_reset,     -- reset_out.reset
			reset_req      => rst_controller_reset_out_reset_req, --          .reset_req
			reset_req_in0  => '0',                                -- (terminated)
			reset_req_in1  => '0',                                -- (terminated)
			reset_in2      => '0',                                -- (terminated)
			reset_req_in2  => '0',                                -- (terminated)
			reset_in3      => '0',                                -- (terminated)
			reset_req_in3  => '0',                                -- (terminated)
			reset_in4      => '0',                                -- (terminated)
			reset_req_in4  => '0',                                -- (terminated)
			reset_in5      => '0',                                -- (terminated)
			reset_req_in5  => '0',                                -- (terminated)
			reset_in6      => '0',                                -- (terminated)
			reset_req_in6  => '0',                                -- (terminated)
			reset_in7      => '0',                                -- (terminated)
			reset_req_in7  => '0',                                -- (terminated)
			reset_in8      => '0',                                -- (terminated)
			reset_req_in8  => '0',                                -- (terminated)
			reset_in9      => '0',                                -- (terminated)
			reset_req_in9  => '0',                                -- (terminated)
			reset_in10     => '0',                                -- (terminated)
			reset_req_in10 => '0',                                -- (terminated)
			reset_in11     => '0',                                -- (terminated)
			reset_req_in11 => '0',                                -- (terminated)
			reset_in12     => '0',                                -- (terminated)
			reset_req_in12 => '0',                                -- (terminated)
			reset_in13     => '0',                                -- (terminated)
			reset_req_in13 => '0',                                -- (terminated)
			reset_in14     => '0',                                -- (terminated)
			reset_req_in14 => '0',                                -- (terminated)
			reset_in15     => '0',                                -- (terminated)
			reset_req_in15 => '0'                                 -- (terminated)
		);

	reset_reset_n_ports_inv <= not reset_reset_n;

	mm_interconnect_0_output_s1_write_ports_inv <= not mm_interconnect_0_output_s1_write;

	mm_interconnect_0_jtag_uart_avalon_jtag_slave_write_ports_inv <= not mm_interconnect_0_jtag_uart_avalon_jtag_slave_write;

	mm_interconnect_0_jtag_uart_avalon_jtag_slave_read_ports_inv <= not mm_interconnect_0_jtag_uart_avalon_jtag_slave_read;

	mm_interconnect_0_sdram_s1_write_ports_inv <= not mm_interconnect_0_sdram_s1_write;

	mm_interconnect_0_sdram_s1_read_ports_inv <= not mm_interconnect_0_sdram_s1_read;

	mm_interconnect_0_sdram_s1_byteenable_ports_inv <= not mm_interconnect_0_sdram_s1_byteenable;

	rst_controller_reset_out_reset_ports_inv <= not rst_controller_reset_out_reset;

end architecture rtl; -- of nios_system
